## Multiple Lnear Regression And Feature Selection

In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn.linear_model import LinearRegression

sns.set()

In [2]:
data = pd.read_csv('/home/jason/learning/data-science/resources/udemy/simpleLinearRegression/1.02.+Multiple+linear+regression.csv')
data.head()

SAT  Rand 1,2,3   GPA
0  1714           1  2.40
1  1664           3  2.52
2  1760           3  2.54
3  1685           3  2.74
4  1693           2  2.83

In [3]:
x = data[['SAT', 'Rand 1,2,3']]
y = data['GPA']

x.head(), y.head()

(    SAT  Rand 1,2,3
 0  1714           1
 1  1664           3
 2  1760           3
 3  1685           3
 4  1693           2,
 0    2.40
 1    2.52
 2    2.54
 3    2.74
 4    2.83
 Name: GPA, dtype: float64)

In [4]:
lr = LinearRegression()
lr.fit(x, y)

LinearRegression()

In [5]:
lr.coef_

array([ 0.00165354, -0.00826982])

In [6]:
lr.intercept_

0.29603261264909486

### R - Squared

In [7]:
lr.score(x, y)

0.40668119528142843

### Adjusted R - Squared

$R^2_{adj} = 1-(1-R^2)*\frac{n-1}{n-p-1}$

In [8]:
def getAdjustedRSquared(lr, feature, target):
    r2 = lr.score(feature, target)
    shape = feature.shape
    n = shape[0]
    p = shape[1]
    
    adjustedRSquared = 1-(1-r2)*(n-1)/(n-p-1)
    return adjustedRSquared

In [9]:
adjust_r2 = getAdjustedRSquared(lr, x, y)
adjust_r2

0.39203134825134023

## Feature Selection

In [10]:
from sklearn.feature_selection import f_regression

In [11]:
f_regression(x, y)
## It returns two arrays:
## 1. F-Statistics 
## 2. p-values

(array([56.04804786,  0.17558437]), array([7.19951844e-11, 6.76291372e-01]))

In [12]:
p_values = f_regression(x, y)[1]
p_values

array([7.19951844e-11, 6.76291372e-01])

In [13]:
p_values.round(3)

array([0.   , 0.676])

### Summary Table

In [14]:
lr_summary = pd.DataFrame(data=x.columns.values, columns=['features'])
lr_summary

features
0         SAT
1  Rand 1,2,3

In [15]:
lr_summary['coeficients'] = lr.coef_
lr_summary['p-values'] = p_values.round(3)

In [16]:
lr_summary

features  coeficients  p-values
0         SAT     0.001654     0.000
1  Rand 1,2,3    -0.008270     0.676

In [17]:
# since the p-value of Rand1,2,3 feature is greate than 0.05 therefore it does not contribute to the model