In [1]:
%config Completer.use_jedi = False

In [2]:
import pandas as pd
file = pd.read_csv('/home/jason/learning/data-science/resources/zomato/zomato.csv')

In [3]:
file.columns

Index(['Restaurant ID', 'Restaurant Name', 'Country Code', 'City', 'Address',
       'Locality', 'Locality Verbose', 'Longitude', 'Latitude', 'Cuisines',
       'Average Cost for two', 'Currency', 'Has Table booking',
       'Has Online delivery', 'Is delivering now', 'Switch to order menu',
       'Price range', 'Aggregate rating', 'Rating color', 'Rating text',
       'Votes'],
      dtype='object')

In [5]:
import numpy as np

In [19]:
a = np.array([[3,2,1], [6,5,4], [9,8,7]])
np.max(a, axis=1)

array([3, 6, 9])

In [27]:
h1 = np.ones((2,4), dtype='int16')
print(h1)
h2 = np.zeros((2,2), dtype='int16')
print(h2)
np.hstack((h1, h2))

[[1 1 1 1]
 [1 1 1 1]]
[[0 0]
 [0 0]]


array([[1, 1, 1, 1, 0, 0],
       [1, 1, 1, 1, 0, 0]], dtype=int16)